conda-forge/poppler-feedstock

recipe/meta.yaml
See https://github.com/conda-forge/conda-forge.github.io/pull/489
=> build with latest openjpeg

recipe/meta.yaml
Now that the packages are in the channel we can revert the changes from #8
=> revert back the pin

.ci_support/linux_python3.6.yaml, .ci_support/osx_python3.6.yaml, .github/PULL_REQUEST_TEMPLATE.md, recipe/meta.yaml
Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #19.
Here's a checklist to do before merging.
Fixes #19
=> MNT: rerender

.ci_support/linux_.yaml, .ci_support/osx_.yaml, .circleci/config.yml, .travis.yml, README.md, recipe/meta.yaml
Part of the issue we are seeing with our poppler was b/c we did not re-render it recently.
=> Fix matrix

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, .ci_support/osx_64_.yaml, .ci_support/win_64_.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .travis.yml, LICENSE.txt, README.md, azure-pipelines.yml, recipe/cmakelists.win.patch, recipe/meta.yaml
=> poppler 20.09.0

conda-forge.yml
=> [ci skip] [skip ci] [cf admin skip] Run migrations on v0.65 branch

conda-forge.yml
=> [ci skip] [skip ci] [cf admin skip] Migrate on 0.89.x branch

recipe/meta.yaml, recipe/windows-setmode.patch
=> Poppler 21.01.0

recipe/meta.yaml
=> Poppler 20.02.0

.ci_support/migrations/openjpeg24.yaml, .scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, LICENSE.txt, README.md, recipe/meta.yaml
=> Poppler 21.03.0

.ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, README.md, recipe/bld.bat, recipe/install.bat, recipe/install.sh, recipe/meta.yaml
=> Split recipe with Qt support

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/build.sh, recipe/exportsymbols.patch, recipe/glib-mkenums-wrapped.win.patch, recipe/includesystembeforejpeg.patch, recipe/meta.yaml, recipe/windows-data.patch
=> Upstream 22.01.0

.ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, .ci_support/migrations/openjpeg25.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, recipe/meta.yaml
=> Update to v22.10

recipe/exportsymbols.patch, recipe/meta.yaml, recipe/windows-data.patch
=> Update to v23.01

.azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
=> Update to v23.03

.ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, recipe/meta.yaml
=> Update to v23.05

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/run_osx_build.sh, recipe/exportsymbols.patch, recipe/includesystembeforejpeg.patch, recipe/meta.yaml, recipe/windows-data.patch
=> Update to v23.08

recipe/meta.yaml
=> poppler v24.02.0

.scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, build-locally.py, recipe/meta.yaml
=> poppler v24.03.0

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, azure-pipelines.yml, recipe/build.sh, recipe/install.sh, recipe/meta.yaml
=> poppler 24.04.0

.azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_ppc64le_.yaml, .ci_support/osx_arm64_.yaml, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, recipe/meta.yaml
Checklist
*  Reset the build number to `0` (if the version changed)
closes #166
@conda-forge-admin please rerender
I bumped the build-number, but perhaps you would rather not and repo patch the metadata?
=> Add run_exports for poppler

.ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .gitignore, recipe/meta.yaml
A very belated happy new year to you all, thanks for maintaining this!
Checklist
=> Poppler 25.02.0
